-- Base Data
-- Seed optimizado con Batch Inserts

INSERT INTO public.brands (name, slug) SELECT 'GE - General Electric', 'ge-general-electric' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'GE - General Electric');
INSERT INTO public.brands (name, slug) SELECT 'Mabe', 'mabe' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Mabe');
INSERT INTO public.brands (name, slug) SELECT 'Precio Actualizado ', 'precio-actualizado' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Precio Actualizado ');
INSERT INTO public.brands (name, slug) SELECT 'Whirpool', 'whirpool' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Whirpool');
INSERT INTO public.brands (name, slug) SELECT 'Electrolux - Frigidaire', 'electrolux-frigidaire' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Electrolux - Frigidaire');
INSERT INTO public.brands (name, slug) SELECT 'Actuador ', 'actuador' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Actuador ');
INSERT INTO public.brands (name, slug) SELECT 'Genérico', 'genérico' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Genérico');
INSERT INTO public.brands (name, slug) SELECT 'LG', 'lg' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'LG');
INSERT INTO public.brands (name, slug) SELECT 'Sin ISV', 'sin-isv' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Sin ISV');
INSERT INTO public.brands (name, slug) SELECT 'Apply Parts', 'apply-parts' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Apply Parts');
INSERT INTO public.brands (name, slug) SELECT 'Samsung', 'samsung' WHERE NOT EXISTS (SELECT 1 FROM public.brands WHERE name ILIKE 'Samsung');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W1', 'Bolsa W1', 'bolsa-w1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta CW2', 'Canasta CW2', 'canasta-cw2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta CW2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta AV5', 'Canasta AV5', 'canasta-av5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta AV5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'En 0  WHIRLPOOL', 'En 0  WHIRLPOOL', 'en-0-whirlpool' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'En 0  WHIRLPOOL');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta L1', 'Canasta L1', 'canasta-l1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta L1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M3', 'Canasta M3', 'canasta-m3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M1', 'Canasta M1', 'canasta-m1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta CM1', 'Canasta CM1', 'canasta-cm1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta CM1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M2', 'Bolsa M2', 'bolsa-m2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta AV6', 'Canasta AV6', 'canasta-av6' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta AV6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M15', 'Canasta M15', 'canasta-m15' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M15');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Productos en Valencia', 'Productos en Valencia', 'productos-en-valencia' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Productos en Valencia');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W3', 'Bolsa W3', 'bolsa-w3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W2', 'Canasta W2', 'canasta-w2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W4', 'Bolsa W4', 'bolsa-w4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Estante 2', 'Estante 2', 'estante-2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Estante 2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja 1C', 'Caja 1C', 'caja-1c' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja 1C');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'En 0', 'En 0', 'en-0' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'En 0');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa E4', 'Bolsa E4', 'bolsa-e4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa E4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta AV2', 'Canasta AV2', 'canasta-av2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta AV2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M7', 'Bolsa M7', 'bolsa-m7' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Estante 3', 'Estante 3', 'estante-3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Estante 3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Estante 1', 'Estante 1', 'estante-1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Estante 1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Galera', 'Galera', 'galera' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Galera');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta AV4', 'Canasta AV4', 'canasta-av4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta AV4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'En 0 Mabe / Ge', 'En 0 Mabe / Ge', 'en-0-mabe-ge' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'En 0 Mabe / Ge');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'En 0 Electrolux', 'En 0 Electrolux', 'en-0-electrolux' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'En 0 Electrolux');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta AV3', 'Canasta AV3', 'canasta-av3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta AV3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta 1', 'Canasta 1', 'canasta-1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta 1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta ES1', 'Canasta ES1', 'canasta-es1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta ES1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Revisar y asignar', 'Revisar y asignar', 'revisar-y-asignar' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Revisar y asignar');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja CM', 'Caja CM', 'caja-cm' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja CM');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'N', 'N', 'n' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'N');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa E3', 'Bolsa E3', 'bolsa-e3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa E3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Estante 4', 'Estante 4', 'estante-4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Estante 4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Cuarto China', 'Cuarto China', 'cuarto-china' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Cuarto China');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M13', 'Canasta M13', 'canasta-m13' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M13');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta V2', 'Canasta V2', 'canasta-v2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta V2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M8', 'Canasta M8', 'canasta-m8' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M8');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W1.2', 'Bolsa W1.2', 'bolsa-w12' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W1.2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M5', 'Bolsa M5', 'bolsa-m5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V9.5', 'Bolsa V9.5', 'bolsa-v95' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V9.5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta V3', 'Canasta V3', 'canasta-v3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta V3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V9.3', 'Bolsa V9.3', 'bolsa-v93' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V9.3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V9.4', 'Bolsa V9.4', 'bolsa-v94' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V9.4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa E5', 'Bolsa E5', 'bolsa-e5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa E5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa L3.1', 'Bolsa L3.1', 'bolsa-l31' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa L3.1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V9.2', 'Bolsa V9.2', 'bolsa-v92' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V9.2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M16', 'Canasta M16', 'canasta-m16' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M16');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'En 0 Lav LG', 'En 0 Lav LG', 'en-0-lav-lg' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'En 0 Lav LG');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M2', 'Canasta M2', 'canasta-m2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W1', 'Canasta W1', 'canasta-w1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta E6', 'Canasta E6', 'canasta-e6' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta E6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W8', 'Canasta W8', 'canasta-w8' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W8');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta E4', 'Canasta E4', 'canasta-e4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta E4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta E1', 'Canasta E1', 'canasta-e1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta E1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta E3', 'Canasta E3', 'canasta-e3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta E3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta V1', 'Canasta V1', 'canasta-v1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta V1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W8', 'Bolsa W8', 'bolsa-w8' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W8');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W4', 'Canasta W4', 'canasta-w4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'En 0 varios', 'En 0 varios', 'en-0-varios' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'En 0 varios');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M6', 'Canasta M6', 'canasta-m6' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa ES 8.1', 'Bolsa ES 8.1', 'bolsa-es-81' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa ES 8.1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W7', 'Canasta W7', 'canasta-w7' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W1.7', 'Bolsa W1.7', 'bolsa-w17' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W1.7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W5', 'Canasta W5', 'canasta-w5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta W3', 'Canasta W3', 'canasta-w3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta W3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W6', 'Bolsa W6', 'bolsa-w6' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C1', 'Caja C1', 'caja-c1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta CW1', 'Canasta CW1', 'canasta-cw1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta CW1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M6', 'Bolsa M6', 'bolsa-m6' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M7', 'Canasta M7', 'canasta-m7' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta AV1', 'Canasta AV1', 'canasta-av1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta AV1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W1.4', 'Bolsa W1.4', 'bolsa-w14' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W1.4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C9', 'Caja C9', 'caja-c9' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C9');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Cuarto ADV', 'Cuarto ADV', 'cuarto-adv' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Cuarto ADV');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V9.6', 'Bolsa V9.6', 'bolsa-v96' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V9.6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M5', 'Canasta M5', 'canasta-m5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M4', 'Bolsa M4', 'bolsa-m4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M9', 'Canasta M9', 'canasta-m9' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M9');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W2', 'Bolsa W2', 'bolsa-w2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W7', 'Bolsa W7', 'bolsa-w7' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C5', 'Caja C5', 'caja-c5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C8', 'Caja C8', 'caja-c8' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C8');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta A1', 'Canasta A1', 'canasta-a1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta A1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta A2', 'Canasta A2', 'canasta-a2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta A2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M12', 'Canasta M12', 'canasta-m12' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M12');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta E7', 'Canasta E7', 'canasta-e7' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta E7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta E2', 'Canasta E2', 'canasta-e2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta E2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M2.6', 'Bolsa M2.6', 'bolsa-m26' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M2.6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M1', 'Bolsa M1', 'bolsa-m1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa E5.1', 'Bolsa E5.1', 'bolsa-e51' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa E5.1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V9.7', 'Bolsa V9.7', 'bolsa-v97' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V9.7');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C2', 'Caja C2', 'caja-c2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta 3', 'Canasta 3', 'canasta-3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta 3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Servicios', 'Servicios', 'servicios' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Servicios');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa L1', 'Bolsa L1', 'bolsa-l1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa L1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Usado', 'Usado', 'usado' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Usado');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M2.8', 'Bolsa M2.8', 'bolsa-m28' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M2.8');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa ES 8.2', 'Bolsa ES 8.2', 'bolsa-es-82' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa ES 8.2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa W5', 'Bolsa W5', 'bolsa-w5' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa W5');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Varios', 'Varios', 'varios' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Varios');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja', 'Caja', 'caja' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V1', 'Bolsa V1', 'bolsa-v1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C3', 'Caja C3', 'caja-c3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C4', 'Caja C4', 'caja-c4' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C4');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa V2', 'Bolsa V2', 'bolsa-v2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa V2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Caja C6', 'Caja C6', 'caja-c6' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Caja C6');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa E2', 'Bolsa E2', 'bolsa-e2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa E2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M3', 'Bolsa M3', 'bolsa-m3' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M3');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M2.9', 'Bolsa M2.9', 'bolsa-m29' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M2.9');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa E1', 'Bolsa E1', 'bolsa-e1' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa E1');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M11', 'Canasta M11', 'canasta-m11' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M11');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta M10', 'Canasta M10', 'canasta-m10' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta M10');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Canasta 2', 'Canasta 2', 'canasta-2' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Canasta 2');
INSERT INTO public.categories (name_es, name_en, slug) SELECT 'Bolsa M2.3', 'Bolsa M2.3', 'bolsa-m23' WHERE NOT EXISTS (SELECT 1 FROM public.categories WHERE name_es ILIKE 'Bolsa M2.3');
INSERT INTO public.warehouses (name) SELECT 'Repuestos Carro 🚐' WHERE NOT EXISTS (SELECT 1 FROM public.warehouses WHERE name ILIKE 'Repuestos Carro 🚐');
INSERT INTO public.warehouses (name) SELECT 'Repuestos Tecni Express / Principal ⚒️🏠' WHERE NOT EXISTS (SELECT 1 FROM public.warehouses WHERE name ILIKE 'Repuestos Tecni Express / Principal ⚒️🏠');
INSERT INTO public.warehouses (name) SELECT 'Repuestos Tienda 2 / SPS Altos V 🏡' WHERE NOT EXISTS (SELECT 1 FROM public.warehouses WHERE name ILIKE 'Repuestos Tienda 2 / SPS Altos V 🏡');
INSERT INTO public.warehouses (name) SELECT 'Tienda Altos Valencia II / SPS' WHERE NOT EXISTS (SELECT 1 FROM public.warehouses WHERE name ILIKE 'Tienda Altos Valencia II / SPS');